#!/usr/local/bin/bash

OID_used_proc=".1.3.6.1.4.1.9.9.48.1.1.1.5.1"
OID_free_proc=".1.3.6.1.4.1.9.9.48.1.1.1.6.1"
OID_used_io=".1.3.6.1.4.1.9.9.48.1.1.1.5.2"
OID_free_io=".1.3.6.1.4.1.9.9.48.1.1.1.6.2"

HOST=$1
COMMUNITY=$2
WARN=$3
CRIT=$4

RES=0
function my_snmp_get () {
 RES=$(/usr/local/bin/snmpget -v2c -c$COMMUNITY $HOST $1 | /usr/bin/awk '{print $4 }')
}

my_snmp_get $OID_used_proc
used_proc=$RES

my_snmp_get $OID_free_proc
free_proc=$RES

my_snmp_get $OID_used_io
used_io=$RES

my_snmp_get $OID_free_io
free_io=$RES

let "totalproc = $used_proc + $free_proc"
let "totalio = $used_io + $free_io"
let "freeproc_per = $free_proc * 100 / $totalproc"
let "freeio_per = $free_io * 100 / $totalio"

echo "Memory OK - Processor pool, FREE - $freeproc_per % I/O pool, FREE - $freeio_per %"

if [[ "$freeproc_per" -lt "$CRIT" || "$freeio_per" -lt "$CRIT" ]]
        then
                exit 2

elif [[ "$WARN" -gt "$freeproc_per" && "$freeproc_per" -gt "$CRIT" || "$WARN" -gt "$freeio_per" && "$freeio_per" -gt "$CRIT" ]]
        then
                exit 1
fi
exit 0

#### README
#### You must accept snmp in your cisco device
#### FREEBSD